import type { Metadata } from "next";
import { Arsenal } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

const arsenal = Arsenal({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-arsenal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arsenal.variable} font-arsenal antialiased overflow-x-hidden`}
      >
        <Nav />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
